export const PORT = 4400;

export const States = [
	{ code: "AN", name: "Andaman and Nicobar Islands" },
	{ code: "AP", name: "Andhra Pradesh" },
	{ code: "AR", name: "Arunachal Pradesh" },
	{ code: "AS", name: "Assam" },
	{ code: "BR", name: "Bihar" },
	{ code: "CH", name: "Chandigarh" },
	{ code: "CT", name: "Chhattisgarh" },
	{ code: "DN", name: "Dadra and Nagar Haveli" },
	{ code: "DD", name: "Daman and Diu" },
	{ code: "DL", name: "Delhi" },
	{ code: "GA", name: "Goa" },
	{ code: "GJ", name: "Gujarat" },
	{ code: "HR", name: "Haryana" },
	{ code: "HP", name: "Himachal Pradesh" },
	{ code: "JK", name: "Jammu and Kashmir" },
	{ code: "JH", name: "Jharkhand" },
	{ code: "KA", name: "Karnataka" },
	{ code: "KL", name: "Kerala" },
	{ code: "LA", name: "Ladakh" },
	{ code: "LD", name: "Lakshadweep" },
	{ code: "MP", name: "Madhya Pradesh" },
	{ code: "MH", name: "Maharashtra" },
	{ code: "MN", name: "Manipur" },
	{ code: "ML", name: "Meghalaya" },
	{ code: "MZ", name: "Mizoram" },
	{ code: "NL", name: "Nagaland" },
	{ code: "OR", name: "Odisha" },
	{ code: "PY", name: "Puducherry" },
	{ code: "PB", name: "Punjab" },
	{ code: "RJ", name: "Rajasthan" },
	{ code: "SK", name: "Sikkim" },
	{ code: "TN", name: "Tamil Nadu" },
	{ code: "TG", name: "Telangana" },
	{ code: "TR", name: "Tripura" },
	{ code: "UP", name: "Uttar Pradesh" },
	{ code: "UT", name: "Uttarakhand" },
	{ code: "WB", name: "West Bengal" },
];

export const Districts = [
	{ districtCode: "TG001", districtName: "ADILABAD" },
	{ districtCode: "MP051", districtName: "AGAR MALWA" },
	{ districtCode: "UP001", districtName: "AGRA" },
	{ districtCode: "MH001", districtName: "AHMADNAGAR" },
	{ districtCode: "GJ001", districtName: "AHMEDABAD" },
	{ districtCode: "MZ001", districtName: "AIZAWL" },
	{ districtCode: "RJ001", districtName: "AJMER" },
	{ districtCode: "MH002", districtName: "AKOLA" },
	{ districtCode: "KL001", districtName: "ALAPPUZHA" },
	{ districtCode: "UP002", districtName: "ALIGARH" },
	{ districtCode: "WB020", districtName: "ALIPURDUAR" },
	{ districtCode: "MP050", districtName: "ALIRAJPUR" },
	{ districtCode: "UP003", districtName: "ALLAHABAD" },
	{ districtCode: "AP026", districtName: "ALLURI SEETHARAMA RA" },
	{ districtCode: "UA001", districtName: "ALMORA" },
	{ districtCode: "RJ002", districtName: "ALWAR" },
	{ districtCode: "HR001", districtName: "AMBALA" },
	{ districtCode: "UP004", districtName: "AMBEDKARNAGAR" },
	{ districtCode: "UP074", districtName: "AMETHI/CSM NAGAR" },
	{ districtCode: "MH003", districtName: "AMRAVATI" },
	{ districtCode: "GJ002", districtName: "AMRELI" },
	{ districtCode: "PB001", districtName: "AMRITSAR" },
	{ districtCode: "UP038", districtName: "AMROHA" },
	{ districtCode: "AP025", districtName: "ANAKAPALLI" },
	{ districtCode: "GJ003", districtName: "ANAND" },
	{ districtCode: "AP002", districtName: "ANANTAPUR" },
	{ districtCode: "JK001", districtName: "ANANTNAG" },
	{ districtCode: "OR001", districtName: "ANGUL" },
	{ districtCode: "AR016", districtName: "ANJAW" },
	{ districtCode: "AP035", districtName: "ANNAMAYA" },
	{ districtCode: "MP047", districtName: "ANUPUR" },
	{ districtCode: "BR001", districtName: "ARARIA" },
	{ districtCode: "GJ027", districtName: "ARAVALLI" },
	{ districtCode: "TN041", districtName: "ARIYALUR" },
	{ districtCode: "BR039", districtName: "ARWAL" },
	{ districtCode: "MP048", districtName: "ASHOKNAGAR" },
	{ districtCode: "UP005", districtName: "AURAIYA" },
	{ districtCode: "BR002", districtName: "AURANGABAD" },
	{ districtCode: "MH004", districtName: "AURANGABAD" },
	{ districtCode: "UP006", districtName: "AZAMGARH" },
	{ districtCode: "JK004", districtName: "BADGAM" },
	{ districtCode: "MP001", districtName: "BADWANI" },
	{ districtCode: "KA001", districtName: "BAGALKOT" },
	{ districtCode: "UA002", districtName: "BAGESHWAR" },
	{ districtCode: "UP007", districtName: "BAGHPAT" },
	{ districtCode: "UP008", districtName: "BAHRAICH" },
	{ districtCode: "AS026", districtName: "BAKSA" },
	{ districtCode: "MP002", districtName: "BALAGHAT" },
	{ districtCode: "OR003", districtName: "BALESHWAR" },
	{ districtCode: "UP009", districtName: "BALLIA" },
	{ districtCode: "CT024", districtName: "BALOD" },
	{ districtCode: "CT021", districtName: "BALODABAZAR" },
	{ districtCode: "CT027", districtName: "BALRAMPUR" },
	{ districtCode: "UP010", districtName: "BALRAMPUR" },
	{ districtCode: "GJ004", districtName: "BANAS KANTHA" },
	{ districtCode: "UP011", districtName: "BANDA" },
	{ districtCode: "JK020", districtName: "BANDIPORA" },
	{ districtCode: "KA002", districtName: "BANGALORE" },
	{ districtCode: "KA027", districtName: "BANGALORE RURAL" },
	{ districtCode: "BR003", districtName: "BANKA" },
	{ districtCode: "WB001", districtName: "BANKURA" },
	{ districtCode: "RJ003", districtName: "BANSWARA" },
	{ districtCode: "AP031", districtName: "BAPATLA" },
	{ districtCode: "UP012", districtName: "BARABANKI" },
	{ districtCode: "JK003", districtName: "BARAMULLAH" },
	{ districtCode: "RJ004", districtName: "BARAN" },
	{ districtCode: "UP013", districtName: "BAREILLY" },
	{ districtCode: "OR004", districtName: "BARGARH" },
	{ districtCode: "RJ005", districtName: "BARMER" },
	{ districtCode: "PB020", districtName: "BARNALA" },
	{ districtCode: "AS001", districtName: "BARPETA" },
	{ districtCode: "CT001", districtName: "BASTAR" },
	{ districtCode: "UP014", districtName: "BASTI" },
	{ districtCode: "PB002", districtName: "BATHINDA" },
	{ districtCode: "BR004", districtName: "BEGUSARAI" },
	{ districtCode: "KA003", districtName: "BELGAUM" },
	{ districtCode: "KA004", districtName: "BELLARY" },
	{ districtCode: "CT023", districtName: "BEMETARA" },
	{ districtCode: "MP003", districtName: "BETUL" },
	{ districtCode: "UP062", districtName: "BHADOHI" },
	{ districtCode: "TG020", districtName: "BHADRADRI KOTHAGUDEM" },
	{ districtCode: "OR006", districtName: "BHADRAK" },
	{ districtCode: "BR006", districtName: "BHAGALPUR" },
	{ districtCode: "MH005", districtName: "BHANDARA" },
	{ districtCode: "RJ006", districtName: "BHARATPUR" },
	{ districtCode: "GJ005", districtName: "BHARUCH" },
	{ districtCode: "GJ006", districtName: "BHAVNAGAR" },
	{ districtCode: "RJ007", districtName: "BHILWARA" },
	{ districtCode: "MP004", districtName: "BHIND" },
	{ districtCode: "HR006", districtName: "BHIWANI" },
	{ districtCode: "BR007", districtName: "BHOJPUR" },
	{ districtCode: "MP005", districtName: "BHOPAL" },
	{ districtCode: "MH006", districtName: "BID" },
	{ districtCode: "KA005", districtName: "BIDAR" },
	{ districtCode: "CT017", districtName: "BIJAPUR" },
	{ districtCode: "KA006", districtName: "BIJAPUR" },
	{ districtCode: "UP015", districtName: "BIJNOR" },
	{ districtCode: "RJ008", districtName: "BIKANER" },
	{ districtCode: "CT002", districtName: "BILASPUR" },
	{ districtCode: "HP001", districtName: "BILASPUR" },
	{ districtCode: "WB003", districtName: "BIRBHUM" },
	{ districtCode: "MN001", districtName: "BISHNUPUR" },
	{ districtCode: "JH001", districtName: "BOKARO" },
	{ districtCode: "OR002", districtName: "BOLANGIR" },
	{ districtCode: "AS024", districtName: "BONGAIGAON" },
	{ districtCode: "GJ029", districtName: "BOTAD" },
	{ districtCode: "OR005", districtName: "BOUDH" },
	{ districtCode: "UP016", districtName: "BUDAUN" },
	{ districtCode: "UP017", districtName: "BULANDSHAHR" },
	{ districtCode: "MH007", districtName: "BULDHANA" },
	{ districtCode: "RJ009", districtName: "BUNDI" },
	{ districtCode: "MP046", districtName: "BURHANPUR" },
	{ districtCode: "BR008", districtName: "BUXAR" },
	{ districtCode: "AS032", districtName: "Biswanath" },
	{ districtCode: "AS003", districtName: "CACHAR" },
	{ districtCode: "HP002", districtName: "CHAMBA" },
	{ districtCode: "UA003", districtName: "CHAMOLI" },
	{ districtCode: "UA004", districtName: "CHAMPAWAT" },
	{ districtCode: "MZ007", districtName: "CHAMPHAI" },
	{ districtCode: "KA007", districtName: "CHAMRAJNAGAR" },
	{ districtCode: "UP018", districtName: "CHANDAULI" },
	{ districtCode: "MN002", districtName: "CHANDEL" },
	{ districtCode: "CH001", districtName: "CHANDIGARH" },
	{ districtCode: "MH008", districtName: "CHANDRAPUR" },
	{ districtCode: "AR001", districtName: "CHANGLANG" },
	{ districtCode: "HR022", districtName: "CHARKI DADRI" },
	{ districtCode: "JH002", districtName: "CHATRA" },
	{ districtCode: "TN043", districtName: "CHENGALPATTU" },
	{ districtCode: "TN001", districtName: "CHENNAI" },
	{ districtCode: "MP006", districtName: "CHHATARPUR" },
	{ districtCode: "MP007", districtName: "CHHINDWARE" },
	{ districtCode: "GJ030", districtName: "CHHOTAUDEPUR" },
	{ districtCode: "KA028", districtName: "CHIKKABALLAPURA" },
	{ districtCode: "KA008", districtName: "CHIKMAGALUR" },
	{ districtCode: "AS002", districtName: "CHIRANG" },
	{ districtCode: "KA009", districtName: "CHITRADURGA" },
	{ districtCode: "UP019", districtName: "CHITRAKUT" },
	{ districtCode: "RJ010", districtName: "CHITTAURGARH" },
	{ districtCode: "AP003", districtName: "CHITTOOR" },
	{ districtCode: "NL015", districtName: "CHUMOUKEDIMA" },
	{ districtCode: "MN003", districtName: "CHURACHANDPUR" },
	{ districtCode: "RJ011", districtName: "CHURU" },
	{ districtCode: "TN002", districtName: "COIMBATORE" },
	{ districtCode: "WB005", districtName: "COOCH BIHAR" },
	{ districtCode: "TN003", districtName: "CUDDALORE" },
	{ districtCode: "AP004", districtName: "CUDDAPAH" },
	{ districtCode: "OR007", districtName: "CUTTACK" },
	{ districtCode: "DL005", districtName: "Central Delhi" },
	{ districtCode: "AS030", districtName: "Charaideo" },
	{ districtCode: "GJ007", districtName: "DAHOD" },
	{ districtCode: "WB006", districtName: "DAKSHIN DINAJPUR" },
	{ districtCode: "KA010", districtName: "DAKSHIN KANNAD" },
	{ districtCode: "DD001", districtName: "DAMAN" },
	{ districtCode: "MP008", districtName: "DAMOH" },
	{ districtCode: "CT003", districtName: "DANTEWADA" },
	{ districtCode: "BR009", districtName: "DARBHANGA" },
	{ districtCode: "WB007", districtName: "DARJEELING" },
	{ districtCode: "AS004", districtName: "DARRANG" },
	{ districtCode: "MP009", districtName: "DATIA" },
	{ districtCode: "RJ012", districtName: "DAUSA" },
	{ districtCode: "KA011", districtName: "DAVANGERE" },
	{ districtCode: "UA005", districtName: "DEHRADUN" },
	{ districtCode: "OR008", districtName: "DEOGARH" },
	{ districtCode: "JH003", districtName: "DEOGHAR" },
	{ districtCode: "UP020", districtName: "DEORIA" },
	{ districtCode: "GJ033", districtName: "DEVBHUMI DWARKA" },
	{ districtCode: "MP010", districtName: "DEWAS" },
	{ districtCode: "TR004", districtName: "DHALAI" },
	{ districtCode: "CT004", districtName: "DHAMTARI" },
	{ districtCode: "JH004", districtName: "DHANBAD" },
	{ districtCode: "MP011", districtName: "DHAR" },
	{ districtCode: "TN004", districtName: "DHARMAPURI" },
	{ districtCode: "KA012", districtName: "DHARWAD" },
	{ districtCode: "RJ013", districtName: "DHAULPUR" },
	{ districtCode: "AS005", districtName: "DHEMAJI" },
	{ districtCode: "OR009", districtName: "DHENKANAL" },
	{ districtCode: "AS006", districtName: "DHUBURI" },
	{ districtCode: "MH010", districtName: "DHULE" },
	{ districtCode: "AR002", districtName: "DIBANG VALLEY" },
	{ districtCode: "AS007", districtName: "DIBRUGARH" },
	{ districtCode: "AS020", districtName: "DIMA HASAO" },
	{ districtCode: "NL008", districtName: "DIMAPUR" },
	{ districtCode: "TN005", districtName: "DINDIGUL" },
	{ districtCode: "MP012", districtName: "DINDORI" },
	{ districtCode: "DD002", districtName: "DIU" },
	{ districtCode: "JK012", districtName: "DODA" },
	{ districtCode: "JH005", districtName: "DUMKA" },
	{ districtCode: "RJ014", districtName: "DUNGARPUR" },
	{ districtCode: "CT005", districtName: "DURG" },
	{ districtCode: "DL011", districtName: "Delhi Shahdara" },
	{ districtCode: "BR026", districtName: "EAST CHAMPARAN" },
	{ districtCode: "ML001", districtName: "EAST GARO HILLS" },
	{ districtCode: "AP005", districtName: "EAST GODAVARI" },
	{ districtCode: "MN009", districtName: "EAST IMPHAL" },
	{ districtCode: "ML008", districtName: "EAST JAINTIA HILLS" },
	{ districtCode: "AR003", districtName: "EAST KHAMENG" },
	{ districtCode: "ML002", districtName: "EAST KHASI HILLS" },
	{ districtCode: "AR004", districtName: "EAST SIANG" },
	{ districtCode: "JH006", districtName: "EAST SINGHBHUM" },
	{ districtCode: "AP029", districtName: "ELURU" },
	{ districtCode: "KL002", districtName: "ERNAKULAM" },
	{ districtCode: "TN006", districtName: "ERODE" },
	{ districtCode: "UP021", districtName: "ETAH" },
	{ districtCode: "UP022", districtName: "ETAWAH" },
	{ districtCode: "DL004", districtName: "East Delhi" },
	{ districtCode: "UP023", districtName: "FAIZABAD" },
	{ districtCode: "HR016", districtName: "FARIDABAD" },
	{ districtCode: "PB003", districtName: "FARIDKOT" },
	{ districtCode: "UP024", districtName: "FARRUKKHABAD" },
	{ districtCode: "HR011", districtName: "FATEHABAD" },
	{ districtCode: "PB004", districtName: "FATEHGARH SAHIB" },
	{ districtCode: "UP025", districtName: "FATEHPUR" },
	{ districtCode: "PB022", districtName: "FAZILKA" },
	{ districtCode: "UP026", districtName: "FIROZABAD" },
	{ districtCode: "PB005", districtName: "FIROZPUR" },
	{ districtCode: "KA013", districtName: "GADAG" },
	{ districtCode: "MH011", districtName: "GADCHIROLI" },
	{ districtCode: "OR010", districtName: "GAJAPATI" },
	{ districtCode: "JK022", districtName: "GANDERBAL" },
	{ districtCode: "GJ008", districtName: "GANDHI NAGAR" },
	{ districtCode: "RJ015", districtName: "GANGANAGAR" },
	{ districtCode: "SK001", districtName: "GANGTOK" },
	{ districtCode: "OR011", districtName: "GANJAM" },
	{ districtCode: "JH007", districtName: "GARHWA" },
	{ districtCode: "CT022", districtName: "GARIYABAND" },
	{ districtCode: "CT028", districtName: "GAURELA PENDRA MARWA" },
	{ districtCode: "UP027", districtName: "GAUTAM BUDH NAGAR" },
	{ districtCode: "BR010", districtName: "GAYA" },
	{ districtCode: "UP028", districtName: "GHAZIABAD" },
	{ districtCode: "UP029", districtName: "GHAZIPUR" },
	{ districtCode: "GJ028", districtName: "GIR SOMNATH" },
	{ districtCode: "JH008", districtName: "GIRIDIH" },
	{ districtCode: "AS008", districtName: "GOALPARA" },
	{ districtCode: "JH009", districtName: "GODDA" },
	{ districtCode: "AS009", districtName: "GOLAGHAT" },
	{ districtCode: "TR007", districtName: "GOMATI" },
	{ districtCode: "UP030", districtName: "GONDA" },
	{ districtCode: "MH033", districtName: "GONDIA" },
	{ districtCode: "BR011", districtName: "GOPALGANJ" },
	{ districtCode: "UP031", districtName: "GORAKHPUR" },
	{ districtCode: "MH012", districtName: "GREATER MUMBAI" },
	{ districtCode: "KA014", districtName: "GULBARGA" },
	{ districtCode: "JH010", districtName: "GUMLA" },
	{ districtCode: "MP014", districtName: "GUNA" },
	{ districtCode: "AP006", districtName: "GUNTUR" },
	{ districtCode: "PB006", districtName: "GURDASPUR" },
	{ districtCode: "HR002", districtName: "GURGAON" },
	{ districtCode: "MP015", districtName: "GWALIOR" },
	{ districtCode: "SK004", districtName: "GYALSHING" },
	{ districtCode: "AS010", districtName: "HAILAKANDI" },
	{ districtCode: "HP003", districtName: "HAMIRPUR" },
	{ districtCode: "UP032", districtName: "HAMIRPUR" },
	{ districtCode: "RJ016", districtName: "HANUMANGARH" },
	{ districtCode: "UP077", districtName: "HAPUR" },
	{ districtCode: "MP016", districtName: "HARDA" },
	{ districtCode: "UP033", districtName: "HARDOI" },
	{ districtCode: "UA006", districtName: "HARIDWAR" },
	{ districtCode: "KA015", districtName: "HASSAN" },
	{ districtCode: "UP034", districtName: "HATHRAS" },
	{ districtCode: "KA016", districtName: "HAVERI" },
	{ districtCode: "JH011", districtName: "HAZARIBAGH" },
	{ districtCode: "MH034", districtName: "HINGOLI" },
	{ districtCode: "HR007", districtName: "HISAR" },
	{ districtCode: "MZ009", districtName: "HNAHTHIAL" },
	{ districtCode: "WB008", districtName: "HOOGHLY" },
	{ districtCode: "MP017", districtName: "HOSHANGABAD" },
	{ districtCode: "PB007", districtName: "HOSHIARPUR" },
	{ districtCode: "WB009", districtName: "HOWRAH" },
	{ districtCode: "TG010", districtName: "HYDERABAD" },
	{ districtCode: "AS028", districtName: "Hojai" },
	{ districtCode: "KL003", districtName: "IDUKKI" },
	{ districtCode: "MP018", districtName: "INDORE" },
	{ districtCode: "MP019", districtName: "JABALPUR" },
	{ districtCode: "OR012", districtName: "JAGATSINGHPUR" },
	{ districtCode: "TG013", districtName: "JAGITIAL" },
	{ districtCode: "BR012", districtName: "JAHANABAD" },
	{ districtCode: "MP020", districtName: "JAHBUA" },
	{ districtCode: "ML003", districtName: "JAINTIA HILLS" },
	{ districtCode: "RJ017", districtName: "JAIPUR" },
	{ districtCode: "RJ018", districtName: "JAISALMER" },
	{ districtCode: "OR013", districtName: "JAJPUR" },
	{ districtCode: "PB008", districtName: "JALANDHAR" },
	{ districtCode: "UP035", districtName: "JALAUN" },
	{ districtCode: "MH013", districtName: "JALGAON" },
	{ districtCode: "MH014", districtName: "JALNA" },
	{ districtCode: "RJ019", districtName: "JALOR" },
	{ districtCode: "WB010", districtName: "JALPAIGURI" },
	{ districtCode: "JK005", districtName: "JAMMU" },
	{ districtCode: "GJ009", districtName: "JAMNAGAR" },
	{ districtCode: "JH021", districtName: "JAMTARA" },
	{ districtCode: "BR013", districtName: "JAMUI" },
	{ districtCode: "TG018", districtName: "JANGAON" },
	{ districtCode: "CT006", districtName: "JANJGIR" },
	{ districtCode: "CT007", districtName: "JASHPUR" },
	{ districtCode: "UP036", districtName: "JAUNPUR" },
	{ districtCode: "TG031", districtName: "JAYASHANKAR BHUPALPA" },
	{ districtCode: "HR012", districtName: "JHAJJAR" },
	{ districtCode: "RJ020", districtName: "JHALAWAR" },
	{ districtCode: "UP037", districtName: "JHANSI" },
	{ districtCode: "WB024", districtName: "JHARGRAM" },
	{ districtCode: "OR014", districtName: "JHARSUGUDA" },
	{ districtCode: "RJ021", districtName: "JHUNJHUNUN" },
	{ districtCode: "HR017", districtName: "JIND" },
	{ districtCode: "MN016", districtName: "JIRIBAM" },
	{ districtCode: "RJ022", districtName: "JODHPUR" },
	{ districtCode: "TG025", districtName: "JOGULAMBA GADWAL" },
	{ districtCode: "AS011", districtName: "JORHAT" },
	{ districtCode: "GJ010", districtName: "JUNAGADH" },
	{ districtCode: "BR005", districtName: "KAIMUR" },
	{ districtCode: "HR003", districtName: "KAITHAL" },
	{ districtCode: "MN014", districtName: "KAKCHING" },
	{ districtCode: "AP027", districtName: "KAKINADA" },
	{ districtCode: "OR015", districtName: "KALAHANDI" },
	{ districtCode: "WB021", districtName: "KALIMPONG" },
	{ districtCode: "TN042", districtName: "KALLAKURICHI" },
	{ districtCode: "TG016", districtName: "KAMAREDDY" },
	{ districtCode: "MN015", districtName: "KAMJONG" },
	{ districtCode: "AR023", districtName: "KAMLE" },
	{ districtCode: "AS012", districtName: "KAMRUP" },
	{ districtCode: "TN007", districtName: "KANCHIPURAM" },
	{ districtCode: "OR025", districtName: "KANDHAMAL" },
	{ districtCode: "MN012", districtName: "KANGPOKPI" },
	{ districtCode: "HP004", districtName: "KANGRA" },
	{ districtCode: "CT008", districtName: "KANKER" },
	{ districtCode: "TN008", districtName: "KANNIYAKUMARI" },
	{ districtCode: "UP039", districtName: "KANNUAJ" },
	{ districtCode: "KL004", districtName: "KANNUR" },
	{ districtCode: "UP040", districtName: "KANPUR RURAL" },
	{ districtCode: "UP041", districtName: "KANPUR URBAN" },
	{ districtCode: "PB009", districtName: "KAPURTHALA" },
	{ districtCode: "PY003", districtName: "KARAIKAL" },
	{ districtCode: "RJ023", districtName: "KARAULI" },
	{ districtCode: "AS013", districtName: "KARBI ANGLONG" },
	{ districtCode: "LD001", districtName: "KARGIL" },
	{ districtCode: "TG002", districtName: "KARIM NAGAR" },
	{ districtCode: "AS014", districtName: "KARIMGANJ" },
	{ districtCode: "HR008", districtName: "KARNAL" },
	{ districtCode: "TN009", districtName: "KARUR" },
	{ districtCode: "KL005", districtName: "KASARAGOD" },
	{ districtCode: "UP073", districtName: "KASHI RAM NAGAR" },
	{ districtCode: "JK007", districtName: "KATHUA" },
	{ districtCode: "BR014", districtName: "KATIHAR" },
	{ districtCode: "MP021", districtName: "KATNI" },
	{ districtCode: "UP042", districtName: "KAUSHAMBI" },
	{ districtCode: "CT009", districtName: "KAWARDHA" },
	{ districtCode: "OR016", districtName: "KENDRAPARA" },
	{ districtCode: "OR017", districtName: "KEONJHAR" },
	{ districtCode: "BR015", districtName: "KHAGARIA" },
	{ districtCode: "TG003", districtName: "KHAMMAM" },
	{ districtCode: "MP013", districtName: "KHANDWA" },
	{ districtCode: "MP045", districtName: "KHARGONE" },
	{ districtCode: "MZ010", districtName: "KHAWZAWL" },
	{ districtCode: "GJ011", districtName: "KHEDA" },
	{ districtCode: "OR018", districtName: "KHORDHA" },
	{ districtCode: "TR005", districtName: "KHOWAI" },
	{ districtCode: "JH023", districtName: "KHUNTI" },
	{ districtCode: "HP005", districtName: "KINNAUR" },
	{ districtCode: "NL010", districtName: "KIPHERE" },
	{ districtCode: "BR016", districtName: "KISHANGANJ" },
	{ districtCode: "JK016", districtName: "KISHTWAR" },
	{ districtCode: "KA017", districtName: "KODAGU" },
	{ districtCode: "JH012", districtName: "KODERMA" },
	{ districtCode: "NL001", districtName: "KOHIMA" },
	{ districtCode: "AS015", districtName: "KOKRAJHAR" },
	{ districtCode: "KA018", districtName: "KOLAR" },
	{ districtCode: "MZ006", districtName: "KOLASIB" },
	{ districtCode: "MH015", districtName: "KOLHAPUR" },
	{ districtCode: "WB004", districtName: "KOLKATA" },
	{ districtCode: "KL006", districtName: "KOLLAM" },
	{ districtCode: "TG012", districtName: "KOMRAM BHEEM ASIFABA" },
	{ districtCode: "AP028", districtName: "KONASEEMA" },
	{ districtCode: "CT020", districtName: "KONDAGAON" },
	{ districtCode: "KA019", districtName: "KOPPAL" },
	{ districtCode: "OR019", districtName: "KORAPUT" },
	{ districtCode: "CT010", districtName: "KORBA" },
	{ districtCode: "CT011", districtName: "KORIA" },
	{ districtCode: "RJ024", districtName: "KOTA" },
	{ districtCode: "KL007", districtName: "KOTTAYAM" },
	{ districtCode: "KL008", districtName: "KOZHIKODE" },
	{ districtCode: "AP009", districtName: "KRISHNA" },
	{ districtCode: "TN033", districtName: "KRISHNAGIRI" },
	{ districtCode: "JK021", districtName: "KULGAM" },
	{ districtCode: "HP006", districtName: "KULLU" },
	{ districtCode: "JK010", districtName: "KUPWARA" },
	{ districtCode: "AP010", districtName: "KURNOOL" },
	{ districtCode: "HR013", districtName: "KURUKSHETRA" },
	{ districtCode: "AR015", districtName: "KURUNG KUMEY" },
	{ districtCode: "UP043", districtName: "KUSHINAGAR" },
	{ districtCode: "GJ012", districtName: "KUTCH" },
	{ districtCode: "AS027", districtName: "Kamrup Metro" },
	{ districtCode: "HP007", districtName: "LAHUL & SPITI" },
	{ districtCode: "AS016", districtName: "LAKHIMPUR" },
	{ districtCode: "UP044", districtName: "LAKHIMPUR" },
	{ districtCode: "LK001", districtName: "LAKSHADWEEP" },
	{ districtCode: "UP045", districtName: "LALITPUR" },
	{ districtCode: "JH019", districtName: "LATEHAR" },
	{ districtCode: "MH016", districtName: "LATUR" },
	{ districtCode: "MZ004", districtName: "LAWNGTLAI" },
	{ districtCode: "LD002", districtName: "LEH" },
	{ districtCode: "AR022", districtName: "LEPARADA" },
	{ districtCode: "JH013", districtName: "LOHARDAGA" },
	{ districtCode: "AR005", districtName: "LOHIT" },
	{ districtCode: "AR017", districtName: "LONGDING" },
	{ districtCode: "NL009", districtName: "LONGLENG" },
	{ districtCode: "AR012", districtName: "LOWER DIBANG VALLEY" },
	{ districtCode: "AR021", districtName: "LOWER SIANG" },
	{ districtCode: "AR006", districtName: "LOWER SUBANSIRI" },
	{ districtCode: "BR017", districtName: "LUCKEESARAI" },
	{ districtCode: "UP046", districtName: "LUCKNOW" },
	{ districtCode: "PB010", districtName: "LUDHIANA" },
	{ districtCode: "MZ003", districtName: "LUNGLEI" },
	{ districtCode: "BR018", districtName: "MADHEPURA" },
	{ districtCode: "BR019", districtName: "MADHUBANI" },
	{ districtCode: "TN010", districtName: "MADURAI" },
	{ districtCode: "TG019", districtName: "MAHABUBABAD" },
	{ districtCode: "UP047", districtName: "MAHARAJGANJ" },
	{ districtCode: "CT012", districtName: "MAHASAMUND" },
	{ districtCode: "PY001", districtName: "MAHE" },
	{ districtCode: "HR018", districtName: "MAHENDRAGARH" },
	{ districtCode: "GJ031", districtName: "MAHISAGAR" },
	{ districtCode: "UP048", districtName: "MAHOBA" },
	{ districtCode: "UP049", districtName: "MAINPURI" },
	{ districtCode: "AS035", districtName: "MAJULI" },
	{ districtCode: "KL009", districtName: "MALAPPURAM" },
	{ districtCode: "WB011", districtName: "MALDA" },
	{ districtCode: "PB023", districtName: "MALERKOTLA" },
	{ districtCode: "OR020", districtName: "MALKANGIRI" },
	{ districtCode: "MZ005", districtName: "MAMIT" },
	{ districtCode: "TG030", districtName: "MANCHERIAL" },
	{ districtCode: "HP008", districtName: "MANDI" },
	{ districtCode: "MP022", districtName: "MANDLA" },
	{ districtCode: "MP023", districtName: "MANDSAUR" },
	{ districtCode: "KA020", districtName: "MANDYA" },
	{ districtCode: "SK002", districtName: "MANGAN" },
	{ districtCode: "PB011", districtName: "MANSA" },
	{ districtCode: "UP050", districtName: "MATHURA" },
	{ districtCode: "UP051", districtName: "MAUNATHBHANJAN" },
	{ districtCode: "TN047", districtName: "MAYILADUTHURAI" },
	{ districtCode: "OR021", districtName: "MAYURBHANJ" },
	{ districtCode: "TG004", districtName: "MEDAK" },
	{ districtCode: "TG029", districtName: "MEDCHAL MALKAJGIRI" },
	{ districtCode: "UP052", districtName: "MEERUT" },
	{ districtCode: "TG005", districtName: "MEHABUBNAGAR" },
	{ districtCode: "GJ013", districtName: "MEHSANA" },
	{ districtCode: "HR021", districtName: "MEWAT" },
	{ districtCode: "UP053", districtName: "MIRZAPUR" },
	{ districtCode: "PB012", districtName: "MOGA" },
	{ districtCode: "NL002", districtName: "MOKOKCHUNG" },
	{ districtCode: "NL003", districtName: "MON" },
	{ districtCode: "UP054", districtName: "MORADABAD" },
	{ districtCode: "GJ032", districtName: "MORBI" },
	{ districtCode: "MP024", districtName: "MORENA" },
	{ districtCode: "AS017", districtName: "MORIGAON" },
	{ districtCode: "PB013", districtName: "MUKTSAR" },
	{ districtCode: "TG032", districtName: "MULUGU" },
	{ districtCode: "MH036", districtName: "MUMBAI CITY" },
	{ districtCode: "CT025", districtName: "MUNGELI" },
	{ districtCode: "BR020", districtName: "MUNGER" },
	{ districtCode: "WB013", districtName: "MURSHIDABAD" },
	{ districtCode: "UP055", districtName: "MUZAFFARNAGAR" },
	{ districtCode: "BR021", districtName: "MUZAFFARPUR" },
	{ districtCode: "KA021", districtName: "MYSORE" },
	{ districtCode: "OR022", districtName: "NABARANGAPUR" },
	{ districtCode: "WB014", districtName: "NADIA" },
	{ districtCode: "AS018", districtName: "NAGAON" },
	{ districtCode: "TN011", districtName: "NAGAPATTINAM" },
	{ districtCode: "TG024", districtName: "NAGARKURNOOL" },
	{ districtCode: "RJ025", districtName: "NAGAUR" },
	{ districtCode: "MH017", districtName: "NAGPUR" },
	{ districtCode: "UA007", districtName: "NAINITAL" },
	{ districtCode: "BR022", districtName: "NALANDA" },
	{ districtCode: "AS019", districtName: "NALBARI" },
	{ districtCode: "TG006", districtName: "NALGONDA" },
	{ districtCode: "TN012", districtName: "NAMAKKAL" },
	{ districtCode: "SK003", districtName: "NAMCHI" },
	{ districtCode: "MH018", districtName: "NANDED" },
	{ districtCode: "MH019", districtName: "NANDURBAR" },
	{ districtCode: "AP032", districtName: "NANDYALA" },
	{ districtCode: "TG033", districtName: "NARAYANPET" },
	{ districtCode: "CT018", districtName: "NARAYANPUR" },
	{ districtCode: "GJ014", districtName: "NARMADA" },
	{ districtCode: "MP025", districtName: "NARSIMHAPUR" },
	{ districtCode: "MH020", districtName: "NASHIK" },
	{ districtCode: "GJ015", districtName: "NAVSARI" },
	{ districtCode: "BR023", districtName: "NAWADA" },
	{ districtCode: "OR023", districtName: "NAYAGARH" },
	{ districtCode: "MP026", districtName: "NEEMACH" },
	{ districtCode: "AP014", districtName: "NELLORE" },
	{ districtCode: "AN003", districtName: "NICOBAR" },
	{ districtCode: "TN013", districtName: "NILGIRIS" },
	{ districtCode: "TG011", districtName: "NIRMAL" },
	{ districtCode: "NL014", districtName: "NIULAND" },
	{ districtCode: "MP052", districtName: "NIWARI" },
	{ districtCode: "TG007", districtName: "NIZAMABAD" },
	{ districtCode: "NL012", districtName: "NOKLAK" },
	{ districtCode: "MN013", districtName: "NONEY" },
	{ districtCode: "WB015", districtName: "NORTH 24 PARGANAS" },
	{ districtCode: "ML011", districtName: "NORTH GARO HILLS" },
	{ districtCode: "GO001", districtName: "NORTH GOA" },
	{ districtCode: "TR001", districtName: "NORTH TRIPURA" },
	{ districtCode: "AN002", districtName: "NORTH&MIDDLE ANDAMAN" },
	{ districtCode: "AP036", districtName: "NTR" },
	{ districtCode: "OR024", districtName: "NUAPARHA" },
	{ districtCode: "AR019", districtName: "Namsai" },
	{ districtCode: "DL006", districtName: "New Delhi" },
	{ districtCode: "DL002", districtName: "North Delhi" },
	{ districtCode: "DL003", districtName: "North East Delhi" },
	{ districtCode: "DL001", districtName: "North West Delhi" },
	{ districtCode: "MH009", districtName: "OSMANABAD" },
	{ districtCode: "JH014", districtName: "PAKUR" },
	{ districtCode: "KL010", districtName: "PALAKKAD" },
	{ districtCode: "JH015", districtName: "PALAMAU" },
	{ districtCode: "MH035", districtName: "PALGHAR" },
	{ districtCode: "RJ026", districtName: "PALI" },
	{ districtCode: "AP030", districtName: "PALNADU" },
	{ districtCode: "HR020", districtName: "PALWAL" },
	{ districtCode: "GJ016", districtName: "PANCH MAHAL" },
	{ districtCode: "HR004", districtName: "PANCHKULA" },
	{ districtCode: "HR009", districtName: "PANIPAT" },
	{ districtCode: "MP027", districtName: "PANNA" },
	{ districtCode: "AR014", districtName: "PAPUMPARE" },
	{ districtCode: "MH021", districtName: "PARBHANI" },
	{ districtCode: "AP024", districtName: "PARVATHIPURAM MANYAM" },
	{ districtCode: "WB023", districtName: "PASCHIM BARDHAMAN" },
	{ districtCode: "WB019", districtName: "PASCHIM MEDINIPUR" },
	{ districtCode: "GJ017", districtName: "PATAN" },
	{ districtCode: "KL011", districtName: "PATHANANTHITTA" },
	{ districtCode: "PB021", districtName: "PATHANKOT" },
	{ districtCode: "PB015", districtName: "PATIALA" },
	{ districtCode: "BR025", districtName: "PATNA" },
	{ districtCode: "UA008", districtName: "PAURI" },
	{ districtCode: "TG014", districtName: "PEDDAPALLI" },
	{ districtCode: "TN014", districtName: "PERAMBALUR" },
	{ districtCode: "NL011", districtName: "PEREN" },
	{ districtCode: "NL004", districtName: "PHEK" },
	{ districtCode: "MN011", districtName: "PHERZAWL" },
	{ districtCode: "UP056", districtName: "PILIBHIT" },
	{ districtCode: "UA009", districtName: "PITHORAGARH" },
	{ districtCode: "PY002", districtName: "PONDICHERRY" },
	{ districtCode: "JK011", districtName: "POONCH" },
	{ districtCode: "GJ018", districtName: "PORBANDER" },
	{ districtCode: "AP016", districtName: "PRAKASAM" },
	{ districtCode: "RJ033", districtName: "PRATAPGARH" },
	{ districtCode: "UP057", districtName: "PRATAPGARH" },
	{ districtCode: "TN015", districtName: "PUDUKKOTTAI" },
	{ districtCode: "JK002", districtName: "PULWAMA" },
	{ districtCode: "MH022", districtName: "PUNE" },
	{ districtCode: "WB022", districtName: "PURBA BARDHAMAN" },
	{ districtCode: "WB012", districtName: "PURBA MEDINIPUR" },
	{ districtCode: "OR026", districtName: "PURI" },
	{ districtCode: "BR027", districtName: "PURNIA" },
	{ districtCode: "WB016", districtName: "PURULIA" },
	{ districtCode: "UP058", districtName: "RAE BARELI" },
	{ districtCode: "KA022", districtName: "RAICHUR" },
	{ districtCode: "CT013", districtName: "RAIGARH" },
	{ districtCode: "MH023", districtName: "RAIGARH" },
	{ districtCode: "CT014", districtName: "RAIPUR" },
	{ districtCode: "MP028", districtName: "RAISEN" },
	{ districtCode: "TG015", districtName: "RAJANNA SIRCILLA" },
	{ districtCode: "MP029", districtName: "RAJGARH" },
	{ districtCode: "GJ019", districtName: "RAJKOT" },
	{ districtCode: "CT015", districtName: "RAJNANDGAON" },
	{ districtCode: "JK013", districtName: "RAJOURI" },
	{ districtCode: "RJ027", districtName: "RAJSAMAND" },
	{ districtCode: "KA029", districtName: "RAMANAGARA" },
	{ districtCode: "TN016", districtName: "RAMANATHAPURAM" },
	{ districtCode: "JK019", districtName: "RAMBAN" },
	{ districtCode: "JH024", districtName: "RAMGARH" },
	{ districtCode: "UP059", districtName: "RAMPUR" },
	{ districtCode: "JH016", districtName: "RANCHI" },
	{ districtCode: "TG008", districtName: "RANGAREDDI" },
	{ districtCode: "TN045", districtName: "RANIPET" },
	{ districtCode: "MP030", districtName: "RATLAM" },
	{ districtCode: "MH024", districtName: "RATNAGIRI" },
	{ districtCode: "OR027", districtName: "RAYAGADA" },
	{ districtCode: "JK018", districtName: "REASI" },
	{ districtCode: "MP031", districtName: "REWA" },
	{ districtCode: "HR014", districtName: "REWARI" },
	{ districtCode: "ML007", districtName: "RI BHOI" },
	{ districtCode: "HR019", districtName: "ROHTAK" },
	{ districtCode: "BR028", districtName: "ROHTAS" },
	{ districtCode: "UA010", districtName: "RUDRAPRAYAG" },
	{ districtCode: "PB016", districtName: "RUPNAGAR" },
	{ districtCode: "GJ020", districtName: "SABAR KANTHA" },
	{ districtCode: "MP032", districtName: "SAGAR" },
	{ districtCode: "UP060", districtName: "SAHARANPUR" },
	{ districtCode: "BR029", districtName: "SAHARSA" },
	{ districtCode: "JH017", districtName: "SAHIBGANJ" },
	{ districtCode: "MZ002", districtName: "SAIHA" },
	{ districtCode: "MZ011", districtName: "SAITUAL" },
	{ districtCode: "TN017", districtName: "SALEM" },
	{ districtCode: "BR030", districtName: "SAMASTIPUR" },
	{ districtCode: "JK017", districtName: "SAMBA" },
	{ districtCode: "OR028", districtName: "SAMBALPUR" },
	{ districtCode: "UP075", districtName: "SAMBHAL" },
	{ districtCode: "TG021", districtName: "SANGAREDDY" },
	{ districtCode: "MH025", districtName: "SANGLI" },
	{ districtCode: "PB017", districtName: "SANGRUR" },
	{ districtCode: "UP061", districtName: "SANT KABIR NAGAR" },
	{ districtCode: "JH022", districtName: "SARAIKELA KHARASAWAN" },
	{ districtCode: "BR031", districtName: "SARAN" },
	{ districtCode: "PB019", districtName: "SAS NAGAR" },
	{ districtCode: "MH026", districtName: "SATARA" },
	{ districtCode: "MP033", districtName: "SATNA" },
	{ districtCode: "RJ028", districtName: "SAWAIMADHOPUR" },
	{ districtCode: "MP034", districtName: "SEHORE" },
	{ districtCode: "MN005", districtName: "SENAPATI" },
	{ districtCode: "MP035", districtName: "SEONI" },
	{ districtCode: "TR006", districtName: "SEPAHIJHALA" },
	{ districtCode: "MZ008", districtName: "SERCHHIP" },
	{ districtCode: "BR032", districtName: "SEWAN" },
	{ districtCode: "MP036", districtName: "SHAHDOL" },
	{ districtCode: "UP063", districtName: "SHAHJAHANPUR" },
	{ districtCode: "MP037", districtName: "SHAJAPUR" },
	{ districtCode: "UP076", districtName: "SHAMLI" },
	{ districtCode: "PB014", districtName: "SHD BHAGAT SINGH NGR" },
	{ districtCode: "BR033", districtName: "SHEIKHPURA" },
	{ districtCode: "BR034", districtName: "SHEOHAR" },
	{ districtCode: "MP038", districtName: "SHEOPUR" },
	{ districtCode: "AR024", districtName: "SHI-YOMI" },
	{ districtCode: "HP009", districtName: "SHIMLA" },
	{ districtCode: "KA023", districtName: "SHIMOGA" },
	{ districtCode: "MP039", districtName: "SHIVPURI" },
	{ districtCode: "JK015", districtName: "SHOPIAN" },
	{ districtCode: "UP064", districtName: "SHRAVASTI" },
	{ districtCode: "AR020", districtName: "SIANG" },
	{ districtCode: "AS021", districtName: "SIBSAGAR" },
	{ districtCode: "TG022", districtName: "SIDDIPET" },
	{ districtCode: "UP065", districtName: "SIDHARTHNAGAR" },
	{ districtCode: "MP040", districtName: "SIDHI" },
	{ districtCode: "RJ029", districtName: "SIKAR" },
	{ districtCode: "DN001", districtName: "SILVASSA" },
	{ districtCode: "JH020", districtName: "SIMDEGA" },
	{ districtCode: "MH027", districtName: "SINDHUDURG" },
	{ districtCode: "MP049", districtName: "SINGRAULI" },
	{ districtCode: "HP010", districtName: "SIRMAUR" },
	{ districtCode: "RJ030", districtName: "SIROHI" },
	{ districtCode: "HR005", districtName: "SIRSA" },
	{ districtCode: "BR035", districtName: "SITAMARHI" },
	{ districtCode: "UP066", districtName: "SITAPUR" },
	{ districtCode: "TN018", districtName: "SIVAGANGA" },
	{ districtCode: "HP011", districtName: "SOLAN" },
	{ districtCode: "MH028", districtName: "SOLAPUR" },
	{ districtCode: "OR029", districtName: "SONAPUR" },
	{ districtCode: "UP067", districtName: "SONBHADRA" },
	{ districtCode: "HR010", districtName: "SONIPAT" },
	{ districtCode: "AS022", districtName: "SONITPUR" },
	{ districtCode: "WB017", districtName: "SOUTH 24 PARGANAS" },
	{ districtCode: "AN001", districtName: "SOUTH ANDAMAN" },
	{ districtCode: "ML006", districtName: "SOUTH GARO HILLS" },
	{ districtCode: "GO002", districtName: "SOUTH GOA" },
	{ districtCode: "TR002", districtName: "SOUTH TRIPURA" },
	{ districtCode: "ML012", districtName: "SOUTH WEST GAROHILLS" },
	{ districtCode: "ML010", districtName: "SOUTHWEST KHASI HILS" },
	{ districtCode: "AP033", districtName: "SRI SATHYA SAI" },
	{ districtCode: "AP018", districtName: "SRIKAKULAM" },
	{ districtCode: "JK006", districtName: "SRINAGAR" },
	{ districtCode: "CT019", districtName: "SUKMA" },
	{ districtCode: "UP068", districtName: "SULTANPUR" },
	{ districtCode: "OR030", districtName: "SUNDARGARH" },
	{ districtCode: "BR036", districtName: "SUPAUL" },
	{ districtCode: "CT026", districtName: "SURAJPUR" },
	{ districtCode: "GJ021", districtName: "SURAT" },
	{ districtCode: "GJ022", districtName: "SURENDRANAGAR" },
	{ districtCode: "CT016", districtName: "SURGUJA" },
	{ districtCode: "TG026", districtName: "SURYAPET" },
	{ districtCode: "DL007", districtName: "South Delhi" },
	{ districtCode: "DL010", districtName: "South East Delhi" },
	{ districtCode: "DL008", districtName: "South West Delhi" },
	{ districtCode: "MN006", districtName: "TAMENGLONG" },
	{ districtCode: "GJ026", districtName: "TAPI" },
	{ districtCode: "PB018", districtName: "TARN TARAN" },
	{ districtCode: "AR007", districtName: "TAWANG" },
	{ districtCode: "UA011", districtName: "TEHRI GARHWAL" },
	{ districtCode: "MN010", districtName: "TENGNOUPAL" },
	{ districtCode: "TN019", districtName: "TENI" },
	{ districtCode: "TN046", districtName: "TENKASI" },
	{ districtCode: "MH029", districtName: "THANE" },
	{ districtCode: "TN020", districtName: "THANJAVUR" },
	{ districtCode: "GJ023", districtName: "THE DANGS" },
	{ districtCode: "KL012", districtName: "THIRUVANANTHAPURAM" },
	{ districtCode: "TN021", districtName: "THIRUVARUR" },
	{ districtCode: "MN007", districtName: "THOUBAL" },
	{ districtCode: "KL013", districtName: "THRISSUR" },
	{ districtCode: "MP041", districtName: "TIKAMGARH" },
	{ districtCode: "AS023", districtName: "TINSUKIA" },
	{ districtCode: "AR008", districtName: "TIRAP" },
	{ districtCode: "TN022", districtName: "TIRUCHCHIRAPPALLI" },
	{ districtCode: "TN023", districtName: "TIRUNELVELI" },
	{ districtCode: "TN044", districtName: "TIRUPATHUR" },
	{ districtCode: "AP034", districtName: "TIRUPATI" },
	{ districtCode: "TN040", districtName: "TIRUPUR" },
	{ districtCode: "TN024", districtName: "TIRUVALLUR" },
	{ districtCode: "TN025", districtName: "TIRUVANNAMALAI" },
	{ districtCode: "RJ031", districtName: "TONK" },
	{ districtCode: "NL013", districtName: "TSEMINYU" },
	{ districtCode: "NL005", districtName: "TUENSANG" },
	{ districtCode: "KA024", districtName: "TUMKUR" },
	{ districtCode: "TN026", districtName: "TUTICORIN" },
	{ districtCode: "RJ032", districtName: "UDAIPUR" },
	{ districtCode: "AS025", districtName: "UDALGURI" },
	{ districtCode: "UA012", districtName: "UDHAM SINGH NAGAR" },
	{ districtCode: "JK014", districtName: "UDHAMPUR" },
	{ districtCode: "KA025", districtName: "UDUPI" },
	{ districtCode: "MP042", districtName: "UJJAIN" },
	{ districtCode: "MN008", districtName: "UKHRUL" },
	{ districtCode: "MP043", districtName: "UMARIA" },
	{ districtCode: "HP012", districtName: "UNA" },
	{ districtCode: "TR008", districtName: "UNAKOTI" },
	{ districtCode: "UP069", districtName: "UNNAO" },
	{ districtCode: "AR013", districtName: "UPPER SIANG" },
	{ districtCode: "AR009", districtName: "UPPER SIBANSIRI" },
	{ districtCode: "WB018", districtName: "UTTAR DINAJPUR" },
	{ districtCode: "KA026", districtName: "UTTAR KANNAD" },
	{ districtCode: "UA013", districtName: "UTTARKASHI" },
	{ districtCode: "GJ024", districtName: "VADODARA" },
	{ districtCode: "BR037", districtName: "VAISHALI" },
	{ districtCode: "GJ025", districtName: "VALSAD" },
	{ districtCode: "UP070", districtName: "VARANASI" },
	{ districtCode: "TN027", districtName: "VELLORE" },
	{ districtCode: "MP044", districtName: "VIDISHA" },
	{ districtCode: "KA040", districtName: "VIJAYANAGARA" },
	{ districtCode: "TG028", districtName: "VIKARABAD" },
	{ districtCode: "TN028", districtName: "VILUPPURAM" },
	{ districtCode: "TN029", districtName: "VIRUDUNAGAR" },
	{ districtCode: "AP019", districtName: "VISHAKHAPATNAM" },
	{ districtCode: "AP020", districtName: "VIZIANAGARAM" },
	{ districtCode: "TG023", districtName: "WANAPARTHY" },
	{ districtCode: "TG009", districtName: "WARANGAL" },
	{ districtCode: "TG017", districtName: "WARANGAL RURAL" },
	{ districtCode: "MH030", districtName: "WARDHA" },
	{ districtCode: "MH031", districtName: "WASHIM" },
	{ districtCode: "KL014", districtName: "WAYANAD" },
	{ districtCode: "BR024", districtName: "WEST CHAMPARAN" },
	{ districtCode: "ML004", districtName: "WEST GARO HILLS" },
	{ districtCode: "AP022", districtName: "WEST GODAVARI" },
	{ districtCode: "MN004", districtName: "WEST IMPHAL" },
	{ districtCode: "ML009", districtName: "WEST JAINTIA HILLS" },
	{ districtCode: "AR010", districtName: "WEST KAMENG" },
	{ districtCode: "ML005", districtName: "WEST KHASI HILLS" },
	{ districtCode: "AR011", districtName: "WEST SIANG" },
	{ districtCode: "JH018", districtName: "WEST SINGHBHUM" },
	{ districtCode: "TR003", districtName: "WEST TRIPURA" },
	{ districtCode: "NL006", districtName: "WOKHA" },
	{ districtCode: "DL009", districtName: "West Delhi" },
	{ districtCode: "AS029", districtName: "West Karbi Anglong" },
	{ districtCode: "TG027", districtName: "YADADRI BHUVANAGIRI" },
	{ districtCode: "KA030", districtName: "YADGIR" },
	{ districtCode: "HR015", districtName: "YAMUNANAGAR" },
	{ districtCode: "PY004", districtName: "YANAM" },
	{ districtCode: "MH032", districtName: "YAVATMAL" },
	{ districtCode: "NL007", districtName: "ZUNHEBOTO" },
];
