export const PORT = 4400;

export const States = [{"id":1, "value":"Andhra Pradesh"},
	{"id":2, "value":"Arunachal Pradesh"},
	{"id":3, "value":"Assam"},
	{"id":4, "value":"Bihar"},
	{"id":5, "value":"Chhattisgarh"},
	{"id":6, "value":"Goa"},
	{"id":7, "value":"Gujarat"},
	{"id":8, "value":"Haryana"},
	{"id":9, "value":"Himachal Pradesh"},
	{"id":10, "value":"Jharkhand"},
	{"id":11, "value":"Karnataka"},
	{"id":12, "value":"Kerala"},
	{"id":13, "value":"Madhya Pradesh"},
	{"id":14, "value":"Maharashtra"},
	{"id":15, "value":"Manipur"},
	{"id":16, "value":"Meghalaya"},
	{"id":17, "value":"Mizoram"},
	{"id":18, "value":"Nagaland"},
	{"id":19, "value":"Odisha"},
	{"id":20, "value":"Punjab"},
	{"id":21, "value":"Rajasthan"},
	{"id":22, "value":"Sikkim"},
	{"id":23, "value":"Tamil Nadu"},
	{"id":24, "value":"Telangana"},
	{"id":25, "value":"Tripura"},
	{"id":26, "value":"Uttarakhand"},
	{"id":27, "value":"Uttar Pradesh"},
	{"id":28, "value":"West Bengal"},
	{"id":29, "value":"Andaman and Nicobar Islands"},
	{"id":30, "value":"Chandigarh"},
	{"id":31, "value":"Daman & Diu"},
	{"id":32, "value":"The Government of NCT of Delhi"},
	{"id":33, "value":"Jammu & Kashmir"},
	{"id":34, "value":"Ladakh"},
	{"id":35, "value":"Lakshadweep"},
	{"id":36, "value":"Puducherry"}]

