export const PORT = 4400;

export const States = [
	{ Code: "AN", Name: "Andaman and Nicobar Islands" },
	{ Code: "AP", Name: "Andhra Pradesh" },
	{ Code: "AR", Name: "Arunachal Pradesh" },
	{ Code: "AS", Name: "Assam" },
	{ Code: "BR", Name: "Bihar" },
	{ Code: "CH", Name: "Chandigarh" },
	{ Code: "CT", Name: "Chhattisgarh" },
	{ Code: "DN", Name: "Dadra and Nagar Haveli" },
	{ Code: "DD", Name: "Daman and Diu" },
	{ Code: "DL", Name: "Delhi" },
	{ Code: "GA", Name: "Goa" },
	{ Code: "GJ", Name: "Gujarat" },
	{ Code: "HR", Name: "Haryana" },
	{ Code: "HP", Name: "Himachal Pradesh" },
	{ Code: "JK", Name: "Jammu and Kashmir" },
	{ Code: "JH", Name: "Jharkhand" },
	{ Code: "KA", Name: "Karnataka" },
	{ Code: "KL", Name: "Kerala" },
	{ Code: "LA", Name: "Ladakh" },
	{ Code: "LD", Name: "Lakshadweep" },
	{ Code: "MP", Name: "Madhya Pradesh" },
	{ Code: "MH", Name: "Maharashtra" },
	{ Code: "MN", Name: "Manipur" },
	{ Code: "ML", Name: "Meghalaya" },
	{ Code: "MZ", Name: "Mizoram" },
	{ Code: "NL", Name: "Nagaland" },
	{ Code: "OR", Name: "Odisha" },
	{ Code: "PY", Name: "Puducherry" },
	{ Code: "PB", Name: "Punjab" },
	{ Code: "RJ", Name: "Rajasthan" },
	{ Code: "SK", Name: "Sikkim" },
	{ Code: "TN", Name: "Tamil Nadu" },
	{ Code: "TG", Name: "Telangana" },
	{ Code: "TR", Name: "Tripura" },
	{ Code: "UP", Name: "Uttar Pradesh" },
	{ Code: "UT", Name: "Uttarakhand" },
	{ Code: "WB", Name: "West Bengal" },
];
